name: foundation
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  chopper: 4.0.5
  device_info_plus: 3.2.3
  flutter:
    sdk: flutter
  fairplay_ds:
    path: "../fairplay_ds"
  flutter_bloc: 8.0.1
  flutter_dotenv: 5.0.2
  hive: 2.0.5
  hive_flutter: 1.1.0
  http: 0.13.4
  injectable: 1.5.3
  intl: 0.17.0
  package_info_plus: 1.0.6
  universal_platform: 1.0.0+1
  get_it: 7.2.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  foundation_generator:
    path: "./../foundation_generator"
