targets:
  $default:
    builders:
      foundation_generator:foundation_builder:
        generate_for:
          include:
            - "lib/features/search/**"
            - "lib/theme/**"
            - "lib/routes.dart"
            - "lib/foundation/router/**"
            - "lib/setup.dart"
          exclude:
            - "lib/foundation/context/**"
